---
- name: Start AMC
  service: name=amc
           state=started
           pattern=/etc/init.d/amc
  sudo: yes

- name: Restart AMC
  service: name=amc
           state=restarted
           pattern=/etc/init.d/amc
  sudo: yes
  
- name: Stop AMC
  service: name=amc
           state=stopped
           pattern=/etc/init.d/amc
  sudo: yes